% generateRFSpace.m - generate an orientation-invariant receptive field in the space domain
% 
% Usage: rf = generateRFSpace(fovPix,fovDeg,gaussSigma,xCenter,yCenter,g2_amp,theta)
%
% Input: fovPix - field of view containing the receptive field in pixels
%        fovDeg - same as above in degrees of visual angle
%        gaussSigma - 2-vec specifying sigmas of DoG rf in space, large/small order not important
%        xCenter - x-coordinate of the Gaussian window (in spatial domain) of the RF in degrees
%        yCenter - y-coordinate of the Gaussian window (in spatial domain) of the RF in degrees
%        g2_amp - amplitude of the wider gaussian used for DoG RF (proportion, relative to default gaussian generated by fspecial)
%                 (will default to 0 if both sigmas are the same)
%
% Output: rf - struct containing the following fields:
%              combP1 - RF made by combining the log-Gaussian bandpass filter with the Gaussian window (1st of quadrature pair)
%              combP2 - RF made by combining the log-Gaussian bandpass filter with the Gaussian window (2nd of quadrature pair)
%              fcombP1 - fourier transform of RF made by combining the log-Gaussian bandpass filter with the Gaussian window (1st of quadrature pair)
%              fcombP2 - fourier transform of RF made by combining the log-Gaussian bandpass filter with the Gaussian window (2nd of quadrature pair)
% 
%              legacy fields - may be needed for compatibility with some functions, but functionally the same as combP1/P2 and fcombP1/P2
%              bpP1 - log-Gaussian bandpass component of RF (1st of quadrature pair)
%              fbpP1 - fourier transform of log-Gaussian bandpass component of RF (1st of quadrature pair)
%              bpP2 - log-Gaussian bandpass component of RF (2nd of quadrature pair)
%              fbpP2 - fourier transform of log-Gaussian bandpass component of RF (2nd of quadrature pair)
% 
% AK - reviewed: 11/8/23
               
function rf = generateRFSpace(fovPix,fovDeg,gaussSigma,xCenter,yCenter,g2_amp)

% take care of units
halfFOVPix = fovPix/2; % in pix, from origin @ center to edge, don't include origin pixel
totalFOVPix = halfFOVPix*2;
rfSize = length(-halfFOVPix:halfFOVPix);
halfFOV = fovDeg/2; % in deg
totalFOV = halfFOV*2;
pix2deg = totalFOV/rfSize;
deg2pix = 1/pix2deg;
samplingFreq = rfSize/totalFOV; % in pixels/deg
deltaS = 1/rfSize; % each pixel is this fraction of the FOV
freqRangeCyclesPerImage = 1/(2*deltaS); % this is the maximum frequency (nyquist freq) in cycles/image
freqRangeCyclesPerDeg = freqRangeCyclesPerImage/totalFOV;
freqPix2freqDeg = samplingFreq/rfSize;

rf.params.halfFOVPix = halfFOVPix;
rf.params.totalFOVPix = totalFOVPix;
rf.params.rfSize = rfSize;
rf.params.halfFOV = halfFOV;
rf.params.fovDeg = totalFOV;
rf.params.pix2deg = pix2deg;
rf.params.deg2pix = deg2pix;
rf.params.samplingFreq = samplingFreq;
rf.params.deltaS = deltaS;
rf.params.freqRangeCyclesPerImage = freqRangeCyclesPerImage;
rf.params.freqRangeCyclesPerDeg = freqRangeCyclesPerDeg;
rf.params.freqPix2freqDeg = freqPix2freqDeg;

%% make a 2d gaussian
g1_sigma = gaussSigma(1);
g2_sigma = gaussSigma(2);

if g1_sigma == g2_sigma
    g2_amp = 0; % there should be no second gaussian if the user specifies the same width for both gaussians
end

% generate space and frequency representations of the 2D RF, 2 quadrature phases
[bpP1, bpfP1, bpP2, bpfP2, xCenterPix, yCenterPix] = createQuadratureLogGaussianFiltersSpace(fovPix,fovDeg,g1_sigma,g2_sigma,xCenter,yCenter,g2_amp);

% rescale values between -1 and 1
tempcombine = [bpP1 bpP2];
maxVal = max(max(abs(tempcombine)));
minVal = -maxVal;
bpP1 = (bpP1 - minVal)/(maxVal - minVal);
bpP1 = 2*bpP1 -1;
bpP2 = (bpP2 - minVal)/(maxVal - minVal);
bpP2 = 2*bpP2 -1;

mask = abs(bpP1) > 1e-10;
bpP1 = bpP1 .* mask;
bpP2 = bpP2 .* mask;

rf.combP1 = bpP1;
rf.combP2 = bpP2;
rf.fcombP1 = bpfP1;
rf.fcombP2 = bpfP2;

% calculate a theoretical maximum response given that the stimulus has values between -1 and 1
maxRespP1 = sum(sum(rf.combP1 .* sign(rf.combP1)));
maxRespP2 = sum(sum(rf.combP2 .* sign(rf.combP2)));
rf.maxRespPhInv = sqrt(maxRespP1^2 + maxRespP2^2);

if g1_sigma < g2_sigma
    rf.params.centerSigma = g1_sigma;
    rf.params.surroundSigma = g2_sigma;
else
    rf.params.centerSigma = g2_sigma;
    rf.params.surroundSigma = g1_sigma;
end
rf.params.xCenter = xCenter;
rf.params.yCenter = yCenter;
rf.params.xCenterPix = xCenterPix;
rf.params.yCenterPix = yCenterPix;

% legacy fields - may be needed for compatibility with some functions, but functionally the same as combP1/P2 and fcombP1/P2
rf.bpP1 = bpP1;
rf.fbpP1 = bpfP1;
rf.bpP2 = bpP2;
rf.fbpP2 = bpfP2;
% keyboard

%% plotting
%{
figure(1)
subplot(1,3,1)
imagesc(gaussian2d)
ax = gca;
ax.YDir = 'normal';
set(ax,'XTick',[1 halfFOVPix+1 totalFOVPix+1])
set(ax,'XTickLabel',([1 halfFOVPix+1 totalFOVPix+1]-(halfFOVPix+1))*pix2deg)
set(ax,'YTick',[1 halfFOVPix+1 totalFOVPix+1])
set(ax,'YTickLabel',([1 halfFOVPix+1 totalFOVPix+1]-(halfFOVPix+1))*pix2deg)
axis square
xlabel('Degrees of visual angle')
ylabel('Degrees of visual angle')
title('Gaussian envelope')
subplot(1,3,2)
imagesc(img)
ax = gca;
ax.YDir = 'normal';
set(ax,'XTick',[1 halfFOVPix+1 totalFOVPix+1])
set(ax,'XTickLabel',([1 halfFOVPix+1 totalFOVPix+1]-(halfFOVPix+1))*pix2deg)
set(ax,'YTick',[1 halfFOVPix+1 totalFOVPix+1])
set(ax,'YTickLabel',([1 halfFOVPix+1 totalFOVPix+1]-(halfFOVPix+1))*pix2deg)
colorbar
axis square
xlabel('Degrees of visual angle')
ylabel('Degrees of visual angle')
title('Bandpass Spatial Frequency Filter')
subplot(1,3,3)
imagesc(rf.comb)
ax = gca;
ax.YDir = 'normal';
set(ax,'XTick',[1 halfFOVPix+1 totalFOVPix+1])
set(ax,'XTickLabel',([1 halfFOVPix+1 totalFOVPix+1]-(halfFOVPix+1))*pix2deg)
set(ax,'YTick',[1 halfFOVPix+1 totalFOVPix+1])
set(ax,'YTickLabel',([1 halfFOVPix+1 totalFOVPix+1]-(halfFOVPix+1))*pix2deg)
colorbar
axis square
xlabel('Degrees of visual angle')
ylabel('Degrees of visual angle')
title('Localized Bandpass Filter')

xyBounds = 30; % just controls how far out we want to plot
lowerXpix = halfFOVPix - xyBounds + 1; upperXpix = halfFOVPix + xyBounds + 1;
lowerYpix = halfFOVPix - xyBounds + 1; upperYpix = halfFOVPix + xyBounds + 1;
figure(2)
subplot(1,3,1)
imagesc(abs(fftshift(fgaussian)))
axis square
xlim([lowerXpix upperXpix])
ylim([lowerYpix upperYpix])
ax = gca;
ax.YDir = 'normal';
set(ax,'XTick',[lowerXpix halfFOVPix+1 upperXpix])
set(ax,'XTickLabel',([lowerYpix halfFOVPix+1 upperYpix]-halfFOVPix-1)*freqPix2freqDeg)
set(ax,'YTick',[lowerXpix halfFOVPix+1 upperXpix])
set(ax,'YTickLabel',([lowerXpix halfFOVPix+1 upperXpix]-halfFOVPix-1)*freqPix2freqDeg)
xlabel('X Frequency (cycles/deg)')
ylabel('Y Frequency (cycles/deg)')
title('Gaussian Envelope (frequency representation)')
colormap(gray)
subplot(1,3,2)
imagesc(abs(imgf))
axis square
xlim([lowerXpix upperXpix])
ylim([lowerYpix upperYpix])
ax = gca;
ax.YDir = 'normal';
set(ax,'XTick',[lowerXpix halfFOVPix+1 upperXpix])
set(ax,'XTickLabel',([lowerXpix halfFOVPix+1 upperXpix]-halfFOVPix-1)*freqPix2freqDeg)
set(ax,'YTick',[lowerXpix halfFOVPix+1 upperXpix])
set(ax,'YTickLabel',([lowerXpix halfFOVPix+1 upperXpix]-halfFOVPix-1)*freqPix2freqDeg)
xlabel('X Frequency (cycles/deg)')
ylabel('Y Frequency (cycles/deg)')
title('Log-Gaussian Bandpass Filter')
colormap(gray)
subplot(1,3,3)
imagesc(abs(fftshift(rf.fcomb)))
axis square
xlim([lowerXpix upperXpix])
ylim([lowerYpix upperYpix])
ax = gca;
ax.YDir = 'normal';
set(ax,'XTick',[lowerXpix halfFOVPix+1 upperXpix])
set(ax,'XTickLabel',([lowerXpix halfFOVPix+1 upperXpix]-halfFOVPix-1)*freqPix2freqDeg)
set(ax,'YTick',[lowerXpix halfFOVPix+1 upperXpix])
set(ax,'YTickLabel',([lowerXpix halfFOVPix+1 upperXpix]-halfFOVPix-1)*freqPix2freqDeg)
xlabel('X Frequency (cycles/deg)')
ylabel('Y Frequency (cycles/deg)')
title('Spatially Localized Bandpass Filter')
colormap(gray)
%}
